//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Functions.PowerShell.SDK.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AzPowerShellSdkStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AzPowerShellSdkStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Functions.PowerShell.SDK.resources.AzPowerShellSdkStrings", typeof(AzPowerShellSdkStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add additional information with name {0} to binding {1} because no binding with this name was found.
        /// </summary>
        internal static string AdditionalInformationNoSuchBinding {
            get {
                return ResourceManager.GetString("AdditionalInformationNoSuchBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following problems exist with AdditionalInformation: \n {0}.
        /// </summary>
        internal static string AdditionalInformationProblemsExist {
            get {
                return ResourceManager.GetString("AdditionalInformationProblemsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple bindings with name {0} in function {1}.
        /// </summary>
        internal static string DuplicateBindings {
            get {
                return ResourceManager.GetString("DuplicateBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple functions declared with name: .
        /// </summary>
        internal static string DuplicateFunctions {
            get {
                return ResourceManager.GetString("DuplicateFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t parse the file: {0}.
        /// </summary>
        internal static string FailedToParseFile {
            get {
                return ResourceManager.GetString("FailedToParseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following functions do not have any bindings: {0}.
        /// </summary>
        internal static string FunctionsWithNoBindings {
            get {
                return ResourceManager.GetString("FunctionsWithNoBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function app directory contains functions which rely on host indexing, please remove them or configure this app for host indexing.
        /// </summary>
        internal static string HybridModelDetected {
            get {
                return ResourceManager.GetString("HybridModelDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following problems exist with InputBinding: \n.
        /// </summary>
        internal static string InputBindingProblemsExist {
            get {
                return ResourceManager.GetString("InputBindingProblemsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify a valid binding direction.
        /// </summary>
        internal static string InvalidBindingDirection {
            get {
                return ResourceManager.GetString("InvalidBindingDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid directory.
        /// </summary>
        internal static string InvalidFunctionsAppDirectory {
            get {
                return ResourceManager.GetString("InvalidFunctionsAppDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrectly formatted Event Hub attribute.
        /// </summary>
        internal static string MalformedEventHubAttribute {
            get {
                return ResourceManager.GetString("MalformedEventHubAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BindingName is missing.
        /// </summary>
        internal static string MissingBindingName {
            get {
                return ResourceManager.GetString("MissingBindingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Direction is missing.
        /// </summary>
        internal static string MissingDirection {
            get {
                return ResourceManager.GetString("MissingDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid Functions App - no host.json detected.
        /// </summary>
        internal static string MissingHostJson {
            get {
                return ResourceManager.GetString("MissingHostJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Name is missing.
        /// </summary>
        internal static string MissingName {
            get {
                return ResourceManager.GetString("MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Type is missing.
        /// </summary>
        internal static string MissingType {
            get {
                return ResourceManager.GetString("MissingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Value is missing.
        /// </summary>
        internal static string MissingValue {
            get {
                return ResourceManager.GetString("MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following problems exist with OutputBinding: \n.
        /// </summary>
        internal static string OutputBindingProblemsExist {
            get {
                return ResourceManager.GetString("OutputBindingProblemsExist", resourceCulture);
            }
        }
    }
}
