# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

strategy:
  matrix:
    windows:
      imageName: 'MMS2019TLS'

pool:
    name: '1ES-Hosted-AzFunc'
    demands:
      - ImageOverride -equals $(imageName)

steps:
- pwsh: ./build.ps1 -NoBuild -Bootstrap
  displayName: 'Installing dependencies'

- pwsh: |
    $ErrorActionPreference = "Stop"
    ./build.ps1 -Clean -Configuration Release
  displayName: 'Building PowerShell module'

- pwsh: ./build.ps1 -NoBuild -Test -Configuration Release
  displayName: 'Running tests'

# Add stage to publish to the PowerShell Gallery on release build