jobs:
  - job: UnitTests
    steps:
    - pwsh: ./build.ps1 -NoBuild -Bootstrap
      displayName: 'Installing dependencies'

    - pwsh: |
        $ErrorActionPreference = "Stop"
        ./build.ps1 -Clean -Configuration Release
      displayName: 'Building PowerShell module'

    - pwsh: ./build.ps1 -NoBuild -Test -Configuration Release
      displayName: 'Running tests'